// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-License-Identifier: Apache-2.0

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { nonogramRuns, solveNonogramByLines } from "../src/nonogram-solver.ts";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TARGET_PATH = resolve(PACKAGE_ROOT, "src/nonogram-fixtures.generated.ts");
const CHECK_FLAG = `-${"-"}check`;
const REVISION = "axl-nonogram-v1";
const SIZES = [
  { size: 5, count: 24 },
  { size: 10, count: 32 },
  { size: 15, count: 24 },
] as const;

/** xorshift32 with a fixed seed per size, so the output never changes. */
function random(seed: number): () => number {
  let state = seed >>> 0 || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 0x1_0000_0000;
  };
}

/** Random noise smoothed into blobs, optionally mirrored, so puzzles read as shapes. */
function candidate(size: number, next: () => number): number[] {
  let grid: number[] = Array.from({ length: size * size }, () => (next() < 0.55 ? 1 : 0));
  for (let pass = 0; pass < (size >= 10 ? 2 : 0); pass += 1) {
    grid = grid.map((_, index) => {
      const row = Math.floor(index / size);
      const column = index % size;
      let filled = 0;
      for (let dr = -1; dr <= 1; dr += 1)
        for (let dc = -1; dc <= 1; dc += 1) {
          const r = row + dr;
          const c = column + dc;
          if (r >= 0 && r < size && c >= 0 && c < size) filled += grid[r * size + c] as number;
        }
      return filled >= 5 ? 1 : 0;
    });
  }
  if (next() < 0.5)
    for (let row = 0; row < size; row += 1)
      for (let column = 0; column < Math.floor(size / 2); column += 1)
        grid[row * size + (size - 1 - column)] = grid[row * size + column] as number;
  return grid;
}

function clues(grid: readonly number[], size: number) {
  const rows = Array.from({ length: size }, (_, row) =>
    nonogramRuns(grid.slice(row * size, row * size + size)),
  );
  const columns = Array.from({ length: size }, (_, column) =>
    nonogramRuns(Array.from({ length: size }, (_, row) => grid[row * size + column] as number)),
  );
  return { rows, columns };
}

function generatedSource(): string {
  const fixtures: string[] = [];
  for (const { size, count } of SIZES) {
    const next = random(size * 7919);
    const seen = new Set<string>();
    let accepted = 0;
    for (let attempt = 0; accepted < count; attempt += 1) {
      if (attempt > 200_000) throw new Error(`Could not generate ${count} ${size}x${size} puzzles`);
      const grid = candidate(size, next);
      const filled = grid.reduce((total, cell) => total + cell, 0);
      if (filled < size * size * 0.4 || filled > size * size * 0.68) continue;
      const solution = grid.join("");
      if (seen.has(solution)) continue;
      const { rows, columns } = clues(grid, size);
      if (rows.some((row) => row.length === 0) || columns.some((column) => column.length === 0))
        continue;
      if (!solveNonogramByLines(rows, columns).solved) continue;
      seen.add(solution);
      accepted += 1;
      fixtures.push(
        `  Object.freeze({ id: ${JSON.stringify(`${size}x${size}-${String(accepted).padStart(2, "0")}`)}, size: ${size}, solution: ${JSON.stringify(solution)} }),`,
      );
    }
  }
  return `// SPDX-FileCopyrightText: 2026 Hari Srinivasan
// SPDX-License-Identifier: Apache-2.0
// @generated by packages/extensions/lounge/scripts/generate-nonogram-fixtures.ts; do not edit.

export const NONOGRAM_FIXTURE_SET_REVISION = ${JSON.stringify(REVISION)} as const;

export type NonogramSize = 5 | 10 | 15;

export interface NonogramFixture {
  readonly id: string;
  /** Width and height. */
  readonly size: NonogramSize;
  /** Row-major cells, "1" filled and "0" empty. Every fixture solves by line logic alone. */
  readonly solution: string;
}

export const NONOGRAM_FIXTURES: readonly NonogramFixture[] = Object.freeze([
${fixtures.join("\n")}
]);
`;
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : "";
if (invokedPath === fileURLToPath(import.meta.url)) {
  const source = generatedSource();
  if (process.argv[2] === CHECK_FLAG) {
    const target = resolve(process.cwd(), process.argv[3] ?? TARGET_PATH);
    if (target !== TARGET_PATH)
      throw new Error(`No Nonogram output exists for ${relative(process.cwd(), target)}`);
    if (readFileSync(target, "utf8") !== source) process.exitCode = 1;
  } else writeFileSync(TARGET_PATH, source);
}
